### ISSUE TITLE
Could you explain how it works if mobile browser without support WebAssembly yet ?

### ISSUE THREAD

**Issue by nvcken** [rbalicki2/wasm_website_frontend#1]

**Comment by rbalicki2** [comment]
Hi! Yes, as far as I can tell, no webassembly apps work on mobile yet. But I'm sure that will change at some point. I haven't done enough research yet to understand the timeline.

In the mean time, I'm going to close this repo at some point and I'd urge you to look at a functioning (and not abandoned!) example at https://github.com/rbalicki2/smithy_itunes_search
